spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/list_assistant
    username: test
    password: passw0rd
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect